series: GLFW Graphics
title: Improved Instancing Tutorial
author:
  name: IGME-RIT
  email:
  github: igme-rit
description: This demo adds on the concept of instanced rendering introduced previously.
language: C++
tags:
  - Graphics
extra_resources:
connections:
  - series: GLFW Graphics
    title: Instancing Tutorial
